spring.application.name=Spring Boot Learning
server.port=8085
spring.data.mongodb.uri=${MONGODB_CONNECTION_STRING}
spring.data.mongodb.auto-index-creation=true
spring.security.user.password=test
jwt.secret=${JWT_SECRET}
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true